### ISSUE TITLE
Plain Pasta 1.1.6 after relaunch occupying 4-10% of CPU

### ISSUE THREAD

**Issue by prolitariat** [hisaac/PlainPasta#10]
Would like to help identify root issue. beta testers needed?

**Comment by hisaac** [comment]
Thanks @daemon86. I've got a potential fix in mind, and will send a beta build your way once I get it ready. 👌

**Comment by hisaac** [comment]
@daemon86 When you get a chance, please test the beta build here: https://github.com/hisaac/PlainPasta/releases/tag/1.1.7-beta1 and let me know if it improves the CPU usage.

**Comment by hisaac** [comment]
I've attempted to resolve this by switching to a different method of polling the pasteboard, which is in release 1.2.0. The release should be hitting the App Store soon, so please let me know if this is still an issue. Thanks!
