### ISSUE TITLE
When Copying an Image from a Webpage, the Image is Lost

### ISSUE THREAD

**Issue by foigus** [hisaac/PlainPasta#3]
When Plain Pasta isn't running, I can right-click on an image in a web browser and select "Copy Image" and paste that image into another program.

When Plain Pasta is running, I right-click on an image in a web browser and select "Copy Image":
- The first attempt results in only the URL in the clipboard
- The second attempt results in both the URL and the image in the clipboard

Safari + macOS 10.14.6.

**Comment by hisaac** [comment]
Thanks @foigus, I appreciate the report. I will look into this one.

**Comment by hisaac** [comment]
I took a quick look, and I have a pretty good idea of what's going on here. I should be able to address it soon.

**Comment by hisaac** [comment]
I found a fix for this issue (in commit ee614724fca8f0b18061b0cc815025f5a397d6d2), and it will go out in the next release! Thanks again for this bug report. I will close this issue once I get the next release ready and posted.

**Comment by hisaac** [comment]
This bug has been fixed in version 1.1.0. You can download the new release here: https://github.com/hisaac/PlainPasta/releases/tag/1.1.0

Please let me know if you have any other issues!
